package com.diegoygabriela.backend_novalink.controller;
import com.diegoygabriela.backend_novalink.dtos.UsuarioDTO;
import com.diegoygabriela.backend_novalink.entity.Usuario;
import com.diegoygabriela.backend_novalink.service.Inter.UsuarioService;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import jakarta.validation.Valid;

import java.util.List;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/usuarios")
public class UsuarioController {

    @Autowired
    private UsuarioService usuarioService;
    
    @Autowired
    private ModelMapper modelMapper;

    @PostMapping("/registrar")
    public void registrar(@Valid @RequestBody UsuarioDTO dto) {
        // For new user registration, the ID will be auto-generated by the database
        // The ID field in the DTO will be ignored and set to null
        Usuario usuario = modelMapper.map(dto, Usuario.class);
        usuarioService.insert(usuario);
    }

    @GetMapping("/listar")
    public List<UsuarioDTO> listar() {
        return usuarioService.list().stream()
                .map(usuario -> modelMapper.map(usuario, UsuarioDTO.class))
                .collect(Collectors.toList());
    }

    @DeleteMapping("/eliminar/{id}")
    public void eliminar(@PathVariable("id") Integer id) {
        usuarioService.delete(id);
    }

    @PutMapping("/modificar")
    public void modificar(@Valid @RequestBody UsuarioDTO dto) {
        Usuario usuario = modelMapper.map(dto, Usuario.class);
        usuarioService.insert(usuario); // Insert funciona también como update en JPA
    }

    @GetMapping("/listar-por-id/{id}")
    public UsuarioDTO listarId(@PathVariable("id") Integer id) {
        return modelMapper.map(usuarioService.listId(id), UsuarioDTO.class);
    }
    
    @GetMapping("/listar-por-username/{username}")
    public UsuarioDTO listarUsername(@PathVariable("username") String username) {
        return modelMapper.map(usuarioService.findByUsername(username), UsuarioDTO.class);
    }
}
